-- Esquema actual de Farmacia Ávila (entidades JPA + columnas observadas en Hibernate).
-- No inventa FKs entre venta/cliente/producto: esas relaciones se modelan con enteros.
-- precio_unitario es nullable: ventas anteriores a Fase 3 pueden no tenerlo.

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    apellido VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL
);

CREATE TABLE users_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_users_roles_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_users_roles_role FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE producto (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    precio DOUBLE PRECISION NOT NULL,
    cantidad INTEGER NOT NULL,
    fecha_vencimiento DATE NOT NULL,
    descripcion VARCHAR(200),
    categoria VARCHAR(255) NOT NULL
);

CREATE TABLE cliente (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL,
    apellidos VARCHAR(80) NOT NULL,
    email VARCHAR(255) NOT NULL,
    telefono VARCHAR(255) NOT NULL
);

CREATE TABLE venta (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idcliente INTEGER NOT NULL,
    fecha_registro DATE,
    precio_total DOUBLE PRECISION NOT NULL
);

CREATE TABLE venta_detalle (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idventa INTEGER NOT NULL,
    idproducto INTEGER NOT NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario DOUBLE PRECISION
);
